jobs:
- job: AppService
  displayName: Deploy to App Service
  steps:
  - task: AzureKeyVault@2
    inputs:
      azureSubscription: $(armConnection)
      KeyVaultName: 'ghost-dev-kv'
      SecretsFilter: '*'
      RunAsPreJob: true
  - script: echo "##vso[task.setvariable variable=imageTag]$(npm run --silent my-version)"
    displayName: Image Tag - use app version
    condition: eq(variables.isProduction, 'True')

  - template: ../steps/append-sha.yaml

  - template: ../steps/debug-vars.yaml

  - task: AzureRmWebAppDeployment@4
    displayName: Deploy Web App Container
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: $(armConnection)
      appType: 'webAppContainer'
      WebAppName: $(webAppName)
      deployToSlotOrASE: true
      ResourceGroupName: $(resourceGroup)
      SlotName: 'production'
      DockerNamespace: 'hasdrubal.azurecr.io'
      DockerRepository: 'ghostonazure'
      DockerImageTag: $(imageTag)
      appSettings: -PORT 2368 -WEBSITES_PORT 2368 -NODE_ENV $(nodeEnvName) -ASSETS_BASE_URL "https://$(webAppName).azurewebsites.net"
