jobs:
- job: BuildAndScan
  displayName: Build and Scan
  steps:
  - template: ../steps/debug-vars.yaml

  - task: DockerCompose@0
    inputs:
      action: Build services
      azureSubscriptionEndpoint: armconnection
      azureContainerRegistry: armconnection
      dockerComposeFile: docker-compose.yml
      projectName: $(Build.Repository.Name)
      qualifyImageNames: true
      additionalImageTags: $(Build.BuildId)
      displayName: Build services
      includeSourceTags: true
      includeLatestTag: true

- job: DockerPush
  displayName: Push
  dependsOn: BuildAndScan
  steps:
  - template: ../steps/debug-vars.yaml

  - template: ../steps/append-sha.yaml

  - task: DockerCompose@0
    displayName: Push services
    inputs:
      action: Push services
      azureSubscriptionEndpoint: armconnection
      azureContainerRegistry: armconnection
      dockerComposeFile: docker-compose.yml
      projectName: $(Build.Repository.Name)
      qualifyImageNames: true
      additionalImageTags: $(Build.BuildId)

  - task: DockerCompose@0
    displayName: Lock services
    condition: eq(variables.isTag, 'True')
    inputs:
      action: Lock services
      azureSubscriptionEndpoint: armconnection
      azureContainerRegistry: armconnection
      dockerComposeFile: docker-compose.yml
      projectName: $(Build.Repository.Name)
      qualifyImageNames: true
      outputDockerComposeFile: $(Build.StagingDirectory)/docker-compose.yml