jobs:
- job: BuildAndScan
  displayName: Build and Scan
  steps:
  - task: AzureKeyVault@2
    inputs:
      azureSubscription: $(armConnection)
      KeyVaultName: 'ghost-dev-kv'
      SecretsFilter: '*'
      RunAsPreJob: true
  - template: ../steps/debug-vars.yaml

  - bash: |
      docker build -t $(dockerImage):$(imageTag) .
    displayName: Docker - build

- job: DockerPush
  displayName: Push
  dependsOn: BuildAndScan
  steps:
  - task: AzureKeyVault@2
    inputs:
      azureSubscription: $(armConnection)
      KeyVaultName: 'ghost-dev-kv'
      SecretsFilter: '*'
      RunAsPreJob: true
  - template: ../steps/debug-vars.yaml

  - task: Docker@2
    displayName: Docker - Login
    inputs:
      command: login
      containerRegistry: $(acrConnection)

  - template: ../steps/append-sha.yaml

  - bash: |
      docker build -t $(dockerImage):$(imageTag) .
      docker push $(dockerImage):$(imageTag)
    displayName: Docker - Build and Push

  - task: Docker@2
    displayName: Docker - Logout
    inputs:
      command: logout
      containerRegistry: $(acrConnection)

  - task: AzureCLI@2
    displayName: 'ACR - lock production image'
    condition: eq(variables.isTag, 'True')
    inputs:
      azureSubscription: $(armConnection)
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az acr repository update \
          --name $(dockerRegistry) \
          --image $(imageName):$(imageTag) \
          --write-enabled false