jobs:
- job: BuildAndScan
  displayName: Build and Scan
  steps:
  - task: AzureKeyVault@2
    inputs:
      azureSubscription: $(armConnection)
      KeyVaultName: 'ghost-dev-kv'
      SecretsFilter: '*'
      RunAsPreJob: true
  - template: ../steps/debug-vars.yaml

  - task: DockerCompose@0
    inputs:
      action: Build services
      azureSubscriptionEndpoint: $(armConnection)
      azureContainerRegistry: $(acrConnection)
      dockerComposeFile: docker-compose.yml
      projectName: $(Build.Repository.Name)
      qualifyImageNames: true
      additionalImageTags: $(Build.BuildId)
      displayName: Build services

- job: DockerPush
  displayName: Push
  dependsOn: BuildAndScan
  steps:
  - task: AzureKeyVault@2
    inputs:
      azureSubscription: $(armConnection)
      KeyVaultName: 'ghost-dev-kv'
      SecretsFilter: '*'
      RunAsPreJob: true
  - template: ../steps/debug-vars.yaml

  - task: DockerCompose@0
    displayName: Push services
    inputs:
      action: Push services
      azureSubscriptionEndpoint: $(armConnection)
      azureContainerRegistry: $(acrConnection)
      dockerComposeFile: docker-compose.yml
      projectName: $(Build.Repository.Name)
      qualifyImageNames: true
      additionalImageTags: $(Build.BuildId)

  - task: DockerCompose@0
    displayName: Lock services
    condition: eq(variables.isTag, 'True')
    inputs:
      action: Lock services
      azureSubscriptionEndpoint: $(armConnection)
      azureContainerRegistry: $(acrConnection)
      dockerComposeFile: docker-compose.yml
      projectName: $(Build.Repository.Name)
      qualifyImageNames: true
      outputDockerComposeFile: $(Build.StagingDirectory)/docker-compose.yml